import type { Card } from "@poker-ai/shared";
import { detectFlushDraw, detectStraightDraw } from "./draws.js";
import { fullDeck } from "@poker-ai/shared";

export interface ComboDrawResult {
  isComboDraw: boolean;
  hasFlushDraw: boolean;
  hasStraightDraw: boolean;
  /** The actual union of out cards from both draws, no double-counting. */
  outs: Card[];
  count: number;
}

/**
 * Detects a combo draw: having a flush draw AND a straight draw at once.
 * Outs are the true union of cards that complete either draw -- a card
 * that happens to complete both (right suit AND right rank) is only
 * counted once, since it's still just one card coming off the deck.
 */
export function detectComboDraw(holeCards: readonly Card[], board: readonly Card[]): ComboDrawResult {
  const flush = detectFlushDraw(holeCards, board);
  const straight = detectStraightDraw(holeCards, board);

  const isComboDraw = flush.hasFlushDraw && straight.kind !== "none";

  if (!isComboDraw) {
    return {
      isComboDraw: false,
      hasFlushDraw: flush.hasFlushDraw,
      hasStraightDraw: straight.kind !== "none",
      outs: [],
      count: 0,
    };
  }

  // Build the actual union of out cards. Flush outs: remaining cards of
  // the flush suit. Straight outs: remaining cards of the completing
  // rank(s), any suit. A card that is both (the completing rank, in the
  // flush suit) would be generated by both descriptions -- dedupe by id.
  const known = [...holeCards, ...board];
  const knownIds = new Set(known.map((c) => `${c.rank}${c.suit}`));

  const outCards = new Map<string, Card>();

  for (const c of fullDeck()) {
    const id = `${c.rank}${c.suit}`;
    if (knownIds.has(id)) continue;

    const completesFlush = flush.suit !== null && c.suit === flush.suit;
    const completesStraight = straight.completingRanks.includes(c.rank);

    if (completesFlush || completesStraight) {
      outCards.set(id, c);
    }
  }

  const outs = [...outCards.values()];
  return {
    isComboDraw: true,
    hasFlushDraw: true,
    hasStraightDraw: true,
    outs,
    count: outs.length,
  };
}